import {
  AccountBookOutlined,
  AlertOutlined,
  AppstoreAddOutlined,
  AppstoreOutlined,
  AreaChartOutlined,
  BarChartOutlined,
  BranchesOutlined,
  CarryOutOutlined,
  CheckSquareOutlined,
  CloudServerOutlined,
  CodeOutlined,
  ControlOutlined,
  DashboardOutlined,
  DeploymentUnitOutlined,
  FieldTimeOutlined,
  FileProtectOutlined,
  FundProjectionScreenOutlined,
  FundViewOutlined,
  GiftOutlined,
  GlobalOutlined,
  IdcardOutlined,
  LayoutOutlined,
  LineChartOutlined,
  LinkOutlined,
  OneToOneOutlined,
  PoundOutlined,
  RadarChartOutlined,
  RobotOutlined,
  SendOutlined,
  SettingOutlined,
  SolutionOutlined,
  TeamOutlined,
  ToolOutlined
} from '@ant-design/icons'

const menuIcons = new Map([
  ['dashboardOutlined', DashboardOutlined],
  ['system', SettingOutlined],
  ['monitor', FundProjectionScreenOutlined],
  ['tool', ToolOutlined],
  ['guide', SendOutlined],
  ['areaChartOutlined', AreaChartOutlined],
  ['barChartOutlined', BarChartOutlined],
  ['lineChartOutlined', LineChartOutlined],
  ['accountBookOutlined', AccountBookOutlined],
  ['appstoreAddOutlined', AppstoreAddOutlined],
  ['codeOutlined', CodeOutlined],
  ['controlOutlined', ControlOutlined],
  ['poundOutlined', PoundOutlined],
  ['giftOutlined', GiftOutlined],
  ['fieldTimeOutlined', FieldTimeOutlined],
  ['globalOutlined', GlobalOutlined],
  ['linkOutlined', LinkOutlined],
  ['checkSquareOutlined', CheckSquareOutlined],
  ['radarChartOutlined', RadarChartOutlined],
  ['appstoreOutlined', AppstoreOutlined],
  ['controlOutlined', ControlOutlined],
  ['fundViewOutlined', FundViewOutlined],
  ['idcardOutlined', IdcardOutlined],
  ['oneToOneOutlined', OneToOneOutlined],
  ['teamOutlined', TeamOutlined],
  ['solutionOutlined', SolutionOutlined],
  ['robotOutlined', RobotOutlined],
  ['layoutOutlined', LayoutOutlined],
  ['FileProtectOutlined', FileProtectOutlined],
  ['DeploymentUnitOutlined', DeploymentUnitOutlined],
  ['BranchesOutlined', BranchesOutlined],
  ['CloudServerOutlined', CloudServerOutlined],
  ['CarryOutOutlined', CarryOutOutlined],
  ['AlertOutlined', AlertOutlined]
])
export default menuIcons
